name: Run tests

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Setup
        run: |
          set -ex
          python -m pip install --upgrade pip
          pip install -r octodns/requirements-freeze.txt
      - name: octodns-validate
        run: |
          export AWS_ACCESS_KEY_ID=key
          export AWS_SECRET_ACCESS_KEY=secret
          cd octodns
          octodns-validate --config-file dns.yaml
